FROM node:12-alpine as builder

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN apk --no-cache add python make g++

COPY package*.json ./
RUN npm install


FROM node:12-alpine

WORKDIR /usr/src/service/
COPY --from=builder node_modules node_modules

COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]
